package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
)
type AutoGenerated struct {
	Antibloqueo struct {
		Mobile                   string `json:"mobile"`
		Video                    string `json:"video"`
		CortoAlternativo         string `json:"corto_alternativo"`
		EnableIads               string `json:"enable_iads"`
		EnableAdmobbanners       string `json:"enable_admobbanners"`
		EnableAdmobinterstitials string `json:"enable_admobinterstitials"`
		Alternativo              string `json:"alternativo"`
		Alternativo2             string `json:"alternativo2"`
		Notifications            string `json:"notifications"`
		ResourceID               string `json:"resource_id"`
	} `json:"_antibloqueo"`
	Labels struct {
		A  string `json:"a"`
		A1 string `json:"a1"`
		B  string `json:"b"`
		C  string `json:"c"`
		D  string `json:"d"`
		E  string `json:"e"`
	} `json:"_labels"`
	Timestamp struct {
		Epoch       string `json:"epoch"`
		Fecha       string `json:"fecha"`
		FechaCorta  string `json:"fecha_corta"`
		FechaCorta2 string `json:"fecha_corta2"`
		FechaNice   string `json:"fecha_nice"`
		Dia         string `json:"dia"`
		DiaCorta    string `json:"dia_corta"`
	} `json:"_timestamp"`
	USD struct {
		Transferencia  float64 `json:"transferencia"`
		TransferCucuta float64 `json:"transfer_cucuta"`
		Efectivo       float64 `json:"efectivo"`
		EfectivoReal   float64 `json:"efectivo_real"`
		EfectivoCucuta float64 `json:"efectivo_cucuta"`
		Promedio       float64 `json:"promedio"`
		PromedioReal   float64 `json:"promedio_real"`
		Cencoex        float64 `json:"cencoex"`
		Sicad1         float64 `json:"sicad1"`
		Sicad2         float64 `json:"sicad2"`
		BitcoinRef     float64 `json:"bitcoin_ref"`
		Dolartoday     float64 `json:"dolartoday"`
	} `json:"USD"`
	EUR struct {
		Transferencia  float64 `json:"transferencia"`
		TransferCucuta float64 `json:"transfer_cucuta"`
		Efectivo       float64 `json:"efectivo"`
		EfectivoReal   float64 `json:"efectivo_real"`
		EfectivoCucuta float64 `json:"efectivo_cucuta"`
		Promedio       float64 `json:"promedio"`
		PromedioReal   float64 `json:"promedio_real"`
		Cencoex        float64 `json:"cencoex"`
		Sicad1         float64 `json:"sicad1"`
		Sicad2         float64 `json:"sicad2"`
		Dolartoday     float64 `json:"dolartoday"`
	} `json:"EUR"`
	COL struct {
		Efectivo float64 `json:"efectivo"`
		Transfer float64 `json:"transfer"`
		Compra   float64 `json:"compra"`
		Venta    float64 `json:"venta"`
	} `json:"COL"`
	GOLD struct {
		Rate float64 `json:"rate"`
	} `json:"GOLD"`
	USDVEF struct {
		Rate float64 `json:"rate"`
	} `json:"USDVEF"`
	USDCOL struct {
		Setfxsell     float64 `json:"setfxsell"`
		Setfxbuy      float64 `json:"setfxbuy"`
		Rate          float64 `json:"rate"`
		Ratecash      float64 `json:"ratecash"`
		Ratetrm       float64 `json:"ratetrm"`
		Trmfactor     float64 `json:"trmfactor"`
		Trmfactorcash float64 `json:"trmfactorcash"`
	} `json:"USDCOL"`
	EURUSD struct {
		Rate float64 `json:"rate"`
	} `json:"EURUSD"`
	BCV struct {
		Fecha     string `json:"fecha"`
		FechaNice string `json:"fecha_nice"`
		Liquidez  string `json:"liquidez"`
		Reservas  string `json:"reservas"`
	} `json:"BCV"`
	MISC struct {
		Petroleo string `json:"petroleo"`
		Reservas string `json:"reservas"`
	} `json:"MISC"`
}

func main() {
	response, err := http.Get("https://s3.amazonaws.com/dolartoday/data.json")

	if err != nil {
		fmt.Print(err.Error())
		os.Exit(1)
	}

	responseData, err := ioutil.ReadAll(response.Body)
	if err != nil {
		log.Fatal(err)
	}

	var responseObject AutoGenerated
	json.Unmarshal(responseData, &responseObject)
	fmt.Println("Cucuta:", responseObject.USD.EfectivoCucuta)
	fmt.Println("Today:", responseObject.USD.Transferencia)

}
